[package]
name = "live_delta_calc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-std = "1.10"
hamming = "0.1.3"
futures = "0.3"
rayon = "1.10.0"
emd = "0.1.0"
ndarray = "0.12.1"
ml-distance = "^1.0.0"
distances = "1.7.1"
chrono = "0.4"
